author: Dannii Willis
description: "Interactive Fiction technology: specifications and tests"
email: curiousdannii@gmail.com
encoding: UTF-8
future: true
gfm_quirks: paragraph_end
github: [metadata]
github_username: curiousdannii
google_analytics: UA-7949545-4
header_pages: []
jailed: false
kramdown:
  input: GFM
  hard_wrap: false
theme: minima
title: Dannii's IF Pages